from abc import ABC, abstractmethod
import pandas as pd


class SignalFilter(ABC):
    """Abstract base class for signal filtering strategies.
    
    This interface allows for the injection of alternative data signals (e.g., sentiment,
    macro indicators) to filter or modify trading signals generated by the cointegration model.
    """

    @abstractmethod
    def filter_signals(self, signals: pd.Series, context_data: pd.DataFrame = None) -> pd.Series:
        """Filter or modify trading signals based on external criteria.

        Args:
            signals (pd.Series): Raw trading signals (-1, 0, 1).
            context_data (pd.DataFrame, optional): Additional data for filtering (e.g., sentiment scores).

        Returns:
            pd.Series: Filtered trading signals.
        """
        pass


class PassThroughFilter(SignalFilter):
    """A filter that passes signals through without modification."""

    def filter_signals(self, signals: pd.Series, context_data: pd.DataFrame = None) -> pd.Series:
        return signals


class SentimentFilter(SignalFilter):
    """Example filter that blocks long trades if sentiment is negative."""
    
    def filter_signals(self, signals: pd.Series, context_data: pd.DataFrame = None) -> pd.Series:
        if context_data is None or "sentiment" not in context_data.columns:
            return signals
            
        filtered_signals = signals.copy()
        
        # Block Longs (1) if sentiment is negative (< 0)
        mask_long_block = (signals == 1) & (context_data["sentiment"] < 0)
        filtered_signals[mask_long_block] = 0
        
        # Block Shorts (-1) if sentiment is positive (> 0)
        mask_short_block = (signals == -1) & (context_data["sentiment"] > 0)
        filtered_signals[mask_short_block] = 0
        
        return filtered_signals
